exclude: '.git|.dvc'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-added-large-files
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.12b0]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-isort]

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.931
      hooks:
        - id: mypy
          args: [--ignore-missing-imports]

  -   repo: https://github.com/econchick/interrogate
      rev: 1.5.0
      hooks:
      - id: interrogate

  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
      -   id: pyupgrade
