steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build --build-arg WANDB_TOKEN=${wandb} -t gcr.io/charged-city-337910/secret -f secret.Dockerfile .']
  secretEnv: ["wandb"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/charged-city-337910/secret']
availableSecrets:
  secretManager:
  - versionName: projects/303765552416/secrets/wandb/versions/latest
    env: "wandb"
