<<<<<<< HEAD
#config.yaml

EPOCHS: 10
BATCH_SIZE: 32
LEARNING_RATE: 1e-4
DROPOUT_PROBABILITY: 0.2

N_WORKERS: 4
BEST_VAL: 100000000

BEST_MODEL_PATH: "models/checkpoints/best_model.pth"
CHECKPOINT_PATH: "models/checkpoints/"
=======
HYPERPARAMETERS:
EPOCHS: 100
BATCH_SIZE: 4
LEARNING_RATE: 0.001
DROPOUT_PROBABILITY: 0.2

# config  variables
N_WORKERS: 2
best_val: 0.5 #Why is this in config tho
>>>>>>> 8c97e059b951ce1726dfa564c0ad679db5687a86
